# Generated by Django 3.2.6 on 2024-02-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('loc', models.CharField(max_length=100)),
                ('temp', models.CharField(max_length=100)),
                ('hum', models.CharField(max_length=100)),
                ('light', models.CharField(max_length=100)),
                ('snd', models.CharField(max_length=100)),
            ],
        ),
    ]
