# Generated by Django 5.0 on 2024-04-15 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iot", "0002_auto_20240223_1128"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
