# Generated by Django 5.0 on 2024-04-16 04:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iot", "0005_rename_time_tm1118_log_date_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tm1118_log",
            old_name="date_created",
            new_name="time",
        ),
    ]
