# Generated by Django 5.0 on 2024-04-16 04:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iot", "0006_rename_date_created_tm1118_log_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tm1118_log",
            old_name="time",
            new_name="date_created",
        ),
    ]
