# Generated by Django 3.2.6 on 2024-04-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0008_step'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tm1118_log',
        ),
    ]
