# Generated by Django 3.2.6 on 2024-04-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0009_delete_tm1118_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('loc', models.CharField(max_length=100)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hum', models.DecimalField(decimal_places=2, max_digits=5)),
                ('light', models.DecimalField(decimal_places=2, max_digits=5)),
                ('snd', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
