# Generated by Django 5.0 on 2024-04-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=5)),
                ("node_loc", models.CharField(max_length=10)),
                ("temp", models.IntegerField()),
                ("hum", models.IntegerField()),
                ("light", models.IntegerField()),
                ("snd", models.IntegerField()),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
