# Generated by Django 3.2.6 on 2024-03-15 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Venue_Event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
